# Generated by Django 5.1.6 on 2025-10-30 10:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
