# Generated by Django 5.1.6 on 2025-10-30 10:32

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body2',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
