# Generated by Django 5.1.6 on 2025-10-30 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_emailtemplate_body2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body2',
        ),
    ]
