# Generated by Django 5.1.6 on 2025-10-30 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_remove_emailtemplate_body2'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
