# Generated by Django 5.1.6 on 2025-10-30 11:06

import django.utils.timezone
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_emailtemplate_body2'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='body3',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
