# Generated by Django 5.1.6 on 2025-10-30 11:17

import ckeditor.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0006_emailtemplate_body3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body3',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
