# Generated by Django 5.1.6 on 2025-10-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0007_alter_emailtemplate_body_alter_emailtemplate_body3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body2',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='body3',
        ),
    ]
