# Generated by Django 5.1.6 on 2025-12-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0008_remove_emailtemplate_body2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJobAppliedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('total_applications', models.PositiveIntegerField(blank=True, null=True)),
                ('successful_applications', models.PositiveIntegerField(blank=True, null=True)),
                ('failed_applications', models.PositiveIntegerField(blank=True, null=True)),
                ('all_recievers', models.JSONField(blank=True, default={}, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
