# Generated by Django 5.1.6 on 2025-12-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0009_bulkjobappliedlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkjobappliedlog',
            name='all_recievers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
