# Generated by Django 5.1.6 on 2025-12-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0010_alter_bulkjobappliedlog_all_recievers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjobappliedlog',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bulkjobappliedlog',
            name='job_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
