# Generated by Django 5.1.6 on 2025-12-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0011_bulkjobappliedlog_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkjobappliedlog',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkjobappliedlog',
            name='last_processed_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
