# Generated by Django 5.1.6 on 2025-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_configuration_address_configuration_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='short_title',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
