# Generated by Django 5.1.6 on 2025-02-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='newsletter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
