# Generated by Django 5.1.6 on 2025-02-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='work_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
