# Generated by Django 5.1.6 on 2025-03-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='type',
        ),
    ]
