# Generated by Django 5.1.6 on 2025-11-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_blog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='bg_image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='favicon_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='logo_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
