# Generated by Django 5.1.6 on 2025-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_blog_cover_image_url_carousel_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='team_pictures/'),
        ),
    ]
