# Generated by Django 5.1.6 on 2025-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_teammember_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
