# Generated by Django 5.1.6 on 2025-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_teammember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
