# Generated by Django 5.1.6 on 2025-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_configuration_lat_configuration_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'JSON Data Importer',
                'verbose_name_plural': 'JSON Data Importer',
                'managed': False,
            },
        ),
    ]
